# alacritty.toml

# [env]
# TERM = "xterm-256color"

[font]
size = 11

[font.normal]
family = "Monospace"
style = "Regular"

[font.bold]
family = "Monospace"
style = "Regular"

[font.bold_italic]
family = "Monospace"
style = "Bold Italic"

[font.italic]
family = "Monospace"
style = "Italic"

[window]
title = "Alacritty"
dynamic_title = false
opacity = 0.80
dynamic_padding = true

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
action = "Paste"
key    = "V"
mods   = "Control"

[[keyboard.bindings]]
action = "Copy"
key    = "C"
mods   = "Control"

[[keyboard.bindings]]
action = "Quit"
key    = "Q"
mods   = "Control"

# Cobalt theme

[colors.primary]
background = "#001b33"
foreground = "#ffffff"

[colors.cursor]
text = "#ffffff"
cursor ="#ffffff"

[colors.normal]
black = "#000000"
red = "#ff0000"
green = "#38de21"
yellow = "#ffe50a"
blue = "#1460d2"
magenta = "#ff005d"
cyan = "#00bbbb"
white = "#bbbbbb"

[colors.bright]
black = "#555555"
red = "#f40e17"
green = "#3bd01d"
yellow = "#edc809"
blue = "#5555ff"
magenta = "#ff55ff"
cyan = "#6ae3fa"
white = "#ffffff"
